{
  "id": "00851553",
  "category_semantic": "Very Complex",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery for a 3D model that looks like a workbench. Start by creating an extruded rectangle with a length of approximately 1.05974 units and a width of about 0.362338 units. Extrude the rectangle to a depth equal to the width (0.362338 units) to form the upper part of the workbench. Make the inside of the rectangle hollow by cutting out a smaller rectangle from the center, with dimensions approximately 0.954546 units in length and 0.261039 units in width, and a depth of 0.314632 units.\n\nNow add legs to the left and right side of this object. Each leg is a marginally extruded rectangle with dimensions 0.041039 units in length and 0.136796 units in width, and a height of 0.314632 units. Connect these legs to the bottom of the original surface, ensuring they are centered and perpendicular to the upper surface.\n\nFinally, add a rod connecting the bottom of the left and right leg. The rod should be cylindrical with a diameter slightly less than the width of each leg (approximately 0.108522 units) and a length equal to the distance between the legs. This rod should be positioned to connect the legs near their bottom ends, enhancing the stability of the workbench model.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nb_length:float = 1.05974\nb_width:float = 0.362338\nb_height:float = 0.341991\nbox:cq.Workplane = cq.Workplane(\"XY\").box(b_length, b_width, b_height)\n\ni_length:float = 0.954546\ni_width:float = 0.261039\ni_height:float = 0.314632\nbox_interior:cq.Workplane = cq.Workplane(\"XY\").box(i_length, i_width, i_height)\n\nr_length:float = 0.041039\nr_width:float = 0.136796\nr_height:float = 0.314632\nright_box:cq.Workplane = cq.Workplane(\"XY\").box(r_length,r_width,r_height)\n\nl_length:float = 0.041039\nl_width:float = 0.136796\nl_height:float = 0.314632\nleft_box:cq.Workplane = cq.Workplane(\"XY\").box(l_length,l_width,l_height)\n\nh_length:float = 1.0\ndiameter:float = 0.108522\nhandle:cq.Workplane = cq.Workplane(\"YZ\").cylinder(h_length,diameter/2)\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .union(box)\n    .cut(box_interior.translate((\n        -b_length/2+i_length/2+0.050649,\n        -b_width/2+i_width/2+0.046797,\n        -b_height/2+i_height/2\n    )))\n    .union(right_box.translate((\n        -b_length/2+r_length/2-0.000435,\n        0,\n        -b_height/2-r_height/2+0.04136\n    )))\n    .union(left_box.translate((\n        i_length/2+l_length/2-0.006869,\n        0,\n        -b_height/2-l_height/2\n    )))\n    .union(handle.translate((\n        -0.006869,\n        0,\n        -b_height/2-l_height/2-diameter/2+0.015775\n    )))\n)\n\npart = part.translate((0.22013,0.072078,b_height/2))\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.456,
  "chamfer_distance": 0.00011607750513021238,
  "bbox_similarity": 0.9999994886160842,
  "volume_ratio": 0.9994566365315364,
  "gt_volume": 0.06508838543625788,
  "gen_volume": 0.06505301878539053,
  "gt_bbox": [
    1.0601753,
    0.3623377,
    0.6566233
  ],
  "gen_bbox": [
    1.0601750016212463,
    0.36233799159526825,
    0.6566230058670044
  ]
}