{
  "id": "00997785",
  "category_semantic": "Very Complex",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a complex, tiered 3D object. Begin by drawing a regular hexagon with a side length of 1.50001 units and extrude it to a height of 0.409382 units. Next, draw a smaller square with side lengths of 0.867904 units, centered at the same point as the hexagon. Rotate this square by 45 degrees so that none of its edges are parallel to the edges of the hexagon. Finally, extrude this square upwards by 0.272921 units to create the appearance of a square placed on top of a hexagon.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nb_length:float = 0.867904\nb_height:float = 0.272921\n\nhex_length:float = 1.50001\nhex_height:float = 0.409382\nsides:int = 6\n\nhexagon:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .polygon(sides, hex_length)\n    .extrude(hex_height)\n    .rotate((0,0,1),(0,0,0),45)\n    .faces(\"Z\")\n    .rect(b_length,b_length)\n    .extrude(b_height)\n    .rotate((0,0,1),(0,0,0),45)\n)\n\npart:cq.Workplane = hexagon\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.386,
  "chamfer_distance": 8.197691687070894e-05,
  "bbox_similarity": 0.999287228302837,
  "volume_ratio": 0.9999999234045781,
  "gt_volume": 0.8038659596886636,
  "gen_volume": 0.8038658981162112,
  "gt_bbox": [
    1.3018216,
    1.5,
    0.6823031
  ],
  "gen_bbox": [
    1.2990467548370361,
    1.5000100135803223,
    0.6823030114173889
  ]
}