{
  "id": "00009998",
  "category_semantic": "Complex",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a 3D model. Begin by creating an extruded rectangle with a length of approximately 0.333333 units and a width of approximately 0.066667 units, making the length about 5 times the width. Then, place a cylinder on one side of the rectangle very close to the edge. The cylinder should have a radius of approximately 0.022222 units, which is about 1/3 of the width of the rectangular surface. The height of the rectangle should be 0.083333 units, and the height of the cylinder should be 0.666667 units. Position the cylinder so that it protrudes from the top surface of the rectangle.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nbox_length:float = 0.333333\nbox_width:float = 1.16667\nbox_height:float = 0.083333\n\nbox:cq.Workplane = cq.Workplane(\"XY\").box(box_length, box_width, box_height)\n\ncylinder_diameter:float = 0.166667\ncylinder_height:float = 0.666667\ncylinder_left_padding:float = 0.052435\ncylinder:cq.Workplane = cq.Workplane(\"XY\").cylinder(cylinder_height, cylinder_diameter/2)\n\npart:cq.Workplane = box.add(cylinder.translate((\n    0, \n    -box_width/2 + cylinder_diameter/2 + cylinder_left_padding, \n    box_height/2 + cylinder_height/2\n)))\n\npart = part.translate((-box_length/2, -0.075832, box_height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.406,
  "chamfer_distance": 5.917260109036746e-05,
  "bbox_similarity": 0.9999987528423256,
  "volume_ratio": 1.0008464973264253,
  "gt_volume": 0.04687808469106436,
  "gen_volume": 0.04691776686442328,
  "gt_bbox": [
    0.33333330000000044,
    1.1666667,
    0.75
  ],
  "gen_bbox": [
    0.33333298563957214,
    1.1666699647903442,
    0.75
  ]
}