{
  "id": "00001817",
  "category_semantic": "Complex",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a table with specific dimensions. First, create a rectangular table top with a length of 1.20302 units, a width of 0.55872 units, and a height of 0.020134 units. Then, create four legs, each being a long extruded square with a length and width of 0.060403 units and a height of 0.75 units. Position these legs at each corner of the table top, ensuring they are linked to the bottom of the table top.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 1.20302\nwidth:float = 0.55872\ntable_top_height:float = 0.020134\n\nleg_length:float = 0.060403\nleg_width:float = 0.060403\nleg_height:float = 0.75\n\ntable_top:cq.Workplane = cq.Workplane(\"XY\").box(length, width, table_top_height)\nleg:cq.Workplane = cq.Workplane(\"XY\").box(leg_length, leg_width, leg_height).translate((0, 0, -(leg_height/2)-table_top_height))\n\ndef add_leg(loc: cq.Location) -> cq.Shape:\n    global leg\n    return leg.val().located(loc) #type:ignore\n\nlegs:cq.Workplane = (\n    table_top\n    .faces(\">Z\")\n    .workplane()\n    .rect(length - leg_length, width - leg_width, forConstruction=True)\n    .vertices()\n    .eachpoint(add_leg)\n)\n\ntable:cq.Workplane = table_top.union(legs)\n\npart = table.translate((0, 0, table_top_height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.442,
  "chamfer_distance": 5.6832237112714467e-05,
  "bbox_similarity": 0.9999969705452979,
  "volume_ratio": 0.9999931124235121,
  "gt_volume": 0.024478826578415852,
  "gen_volume": 0.02447865797862546,
  "gt_bbox": [
    1.2030202,
    0.5587248,
    0.77013423
  ],
  "gen_bbox": [
    1.2030199766159058,
    0.5587199926376343,
    0.770134000107646
  ]
}