{
  "id": "00001490",
  "category_semantic": "Moderate",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a cylinder with a height of 0.48649 units and a radius of 0.75 units. Include a central circular cutout with a diameter of 0.243243243243244 units that extends through the entire height of the cylinder.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nheight:float = 0.48649\nradius:float = 0.75\nhole_diameter:float = 0.121621621621622*2\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .cylinder(height, radius)\n    .faces(\">Z\")\n    .hole(hole_diameter, height)\n)\n\npart = part.translate((0, 0, height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')\n\n",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.437,
  "chamfer_distance": 8.382214329998768e-05,
  "bbox_similarity": 0.9998939880493267,
  "volume_ratio": 1.0047046479204516,
  "gt_volume": 0.8328422813668696,
  "gen_volume": 0.8367605110739663,
  "gt_bbox": [
    1.5,
    1.5,
    0.4864865
  ],
  "gen_bbox": [
    1.5,
    1.499533772468567,
    0.48649001121520996
  ]
}