{
  "id": "00675498",
  "category_semantic": "Complex",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a tiered 3D object. Begin by creating a sketch of a rectangle with dimensions approximately 0.75 units by 0.664347 units, where the shorter sides are roughly half the size of the longer sides. Next, sketch a right trapezoid with a height of 0.374227 units and bases of 0.280836 units and 0.562673 units. Attach the longer base of the trapezoid to one end of the rectangle. Finally, extrude this entire sketch to a depth of 0.664347 units to form a tiered, rectangular object.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\nfrom typing import List,Tuple\n\nbox_length:float = 0.75\nbox_height:float = 0.704219\nbottom_padding:float =  0.329992\nheight:float = box_height - 0.329992\nlength:float = 0.280836\ntop_length:float = box_length - 0.187163\n\nwidth:float = 0.664347\n\npts:List[Tuple[float, float]] = [\n    (0,0),\n    (0,height),\n    (top_length,height),\n    (length,0)\n]\n\nangle:cq.Workplane = (\n    cq.Workplane(\"XZ\")\n    .polyline(pts)\n    .close()\n    .extrude(width)\n).rotate((0,0,1),(0,0,0),180).translate((top_length-box_length/2+0.187163,-width/2,-box_height/2+bottom_padding))\n\nbox:cq.Workplane = cq.Workplane(\"XY\").box(box_length,width,box_height)\n\npart:cq.Workplane = box.cut(angle)\npart = part.translate((box_length/2,width/2,-box_height/2))\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.386,
  "chamfer_distance": 0.00010615554911014734,
  "bbox_similarity": 0.9999998982802037,
  "volume_ratio": 1.0000002908000438,
  "gt_volume": 0.2460087074301854,
  "gen_volume": 0.24600877896952833,
  "gt_bbox": [
    0.7500000000000007,
    0.6643469,
    0.7042191
  ],
  "gen_bbox": [
    0.75,
    0.6643469929695129,
    0.7042189836502075
  ]
}