{
  "id": "00038614",
  "category_semantic": "Moderate",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a square-shaped frame with an outer length of 1.5 units, an outer width of 1.5 units, an inside padding of 0.17649 units, and an extrusion height of 0.00265 units.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 1.5\nwidth:float = 1.5\n\ninside_padding:float = 0.17649\nextrude:float = 0.00265\n\noutline:cq.Sketch = (\n    cq.Sketch()\n    .rect(length, width)\n    .rect(length - inside_padding*2, width - inside_padding*2, mode=\"s\")\n)\n\npart:cq.Workplane = cq.Workplane(\"XY\").placeSketch(outline).extrude(extrude)\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.395,
  "chamfer_distance": 1.4803273294409534e-05,
  "bbox_similarity": 0.999629661680959,
  "volume_ratio": 1.0012064381614802,
  "gt_volume": 0.0024730310425402076,
  "gen_volume": 0.0024760146015644535,
  "gt_bbox": [
    1.5,
    1.5,
    0.0026470590000000458
  ],
  "gen_bbox": [
    1.5,
    1.5,
    0.0026499999221414328
  ]
}