{
  "id": "00673788",
  "category_semantic": "Complex",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a large square with dimensions 1.5 by 1.5 units and extrude it to a height of 0.09375 units. Next, cut out a large right triangle from the bottom-right corner of the rectangle. The triangle should have its right angle at the bottom-right corner of the square, with one side along the bottom edge of the square measuring 1.125 units and the other side along the right edge measuring 1.3125 units. Ensure the cut aligns precisely with the square's corner.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\nfrom typing import List,Tuple\n\nlength:float = 1.5 - 0.1875\nwidth:float = 1.5 -0.375\nextrude:float = 0.09375\n\npts:List[Tuple[float, float]] = [(0,0),(0,width),(length,0)]\nangle_cut:cq.Workplane = cq.Workplane(\"ZY\").polyline(pts).close().extrude(extrude)\n\nbox:cq.Workplane = cq.Workplane(\"ZY\").box(1.5,1.5,extrude)\n\npart:cq.Workplane = box.cut(angle_cut.translate((extrude/2,-1.5/2,-1.5/2)))\npart = part.translate((extrude/2,0,0))\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.381,
  "chamfer_distance": 5.040044684504222e-05,
  "bbox_similarity": 1.0,
  "volume_ratio": 1.0,
  "gt_volume": 0.1417236328125,
  "gen_volume": 0.1417236328125,
  "gt_bbox": [
    0.09375,
    1.5,
    1.5
  ],
  "gen_bbox": [
    0.09375,
    1.5,
    1.5
  ]
}