{
  "id": "00003219",
  "category_semantic": "Simple",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a long cylinder with a height of 1.23718 units and a radius of 0.27226 units.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nheight:float = 1.23718\nradius:float = 0.54452/2\n\npart:cq.Workplane  = cq.Workplane(\"XY\").cylinder(height, radius)\n\npart = part.translate((0, 0, height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.441,
  "chamfer_distance": 7.810715700738049e-05,
  "bbox_similarity": 0.9998906695281667,
  "volume_ratio": 1.0046613799450932,
  "gt_volume": 0.2866491920683552,
  "gen_volume": 0.2879853728635398,
  "gt_bbox": [
    0.5445238,
    0.5445238,
    1.237184
  ],
  "gen_bbox": [
    0.5445200204849243,
    0.5443507432937622,
    1.2371799945831299
  ]
}