{
  "id": "00004154",
  "category_semantic": "Moderate",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a 3D box with a length of 0.70588 units, a width of 0.40809 units, and a height of 0.22059 units. The box should have its vertical edges rounded with a fillet radius of 0.08 units. After creating the box, translate it so that its base is centered at the origin.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.70588\nwidth:float =  0.40809\nheight:float = 0.22059\nfillet:float = 0.08\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .box(length, width, height)\n    .edges(\"|Z\")\n    .fillet(fillet)\n)\n\npart = part.translate((length/2, width/2, height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.411,
  "chamfer_distance": 9.198392574114802e-05,
  "bbox_similarity": 0.9999946806651449,
  "volume_ratio": 0.9988229548533758,
  "gt_volume": 0.06239449750552087,
  "gen_volume": 0.06232105636505594,
  "gt_bbox": [
    0.7058823999999999,
    0.4080882,
    0.2205882
  ],
  "gen_bbox": [
    0.7058799862861633,
    0.4080899953842163,
    0.2205899953842163
  ]
}