{
  "id": "00671938",
  "category_semantic": "Very Complex",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a cylindrical object with a height of 0.75 units and a diameter of 0.419231 units. Begin by creating a sketch of two overlapping circles, each with a radius of half the diameter, and then extrude this sketch to the specified height. Position the first cylinder at coordinates (-0.09259, -0.022198, height/2) and the second cylinder at coordinates (0.082574, 0.01872, height/2).",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nheight:float = 0.75\ndiameter:float = 0.419231\n\ncylinder:cq.Workplane = cq.Workplane(\"XY\").cylinder(height, diameter/2)\n\ncylinder = cylinder.translate((-0.09259 ,-0.022198,height/2))\npart = cylinder.union(cylinder.translate((0.175164  ,0.040918 ,0)))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.461,
  "chamfer_distance": 9.531416786404541e-05,
  "bbox_similarity": 0.9991562385004638,
  "volume_ratio": 1.0003029375648151,
  "gt_volume": 0.15819693396170634,
  "gen_volume": 0.15824485775564193,
  "gt_bbox": [
    0.5943845999999999,
    0.4611994,
    0.75
  ],
  "gen_bbox": [
    0.5943882465362549,
    0.4600348025560379,
    0.75
  ]
}