{
  "id": "00007362",
  "category_semantic": "Simple",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a rectangular prism with a length of 0.75 units, a width of 0.06429 units, and a height of 0.03929 units. The prism should be positioned such that its center aligns with the origin in the CAD workspace.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.75\nwidth:float = 0.06429\nheight:float = 0.03929\n\npart:cq.Workplane = cq.Workplane(\"XY\").box(length, width, height)\n\npart = part.translate((length/2, -width/2, height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.406,
  "chamfer_distance": 1.7699922166898914e-05,
  "bbox_similarity": 0.9999413473335707,
  "volume_ratio": 1.0001759652895272,
  "gt_volume": 0.0018941323201530746,
  "gen_volume": 0.0018944656216951933,
  "gt_bbox": [
    0.7500000000000001,
    0.06428570999999997,
    0.03928571000000001
  ],
  "gen_bbox": [
    0.75,
    0.06429000198841095,
    0.03928999975323677
  ]
}