{
  "id": "00039012",
  "category_semantic": "Complex",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a pipe with a thin flange at one end. The pipe should be hollow, constructed using two extrusions: a positive extrusion for the inner circle with a diameter of approximately 0.70248 inches and a height of 0.75 inches, and a negative extrusion for the outer circle with a diameter of 0.825 inches and a height of 0.01125 inches. The outer circle should form a very thin flange at the base of the pipe.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nbase_diameter:float = 0.825\nbase_height:float = 0.01125\n\ntop_diameter:float = base_diameter - 0.0375*2\ntop_height:float = 0.73875\n\ncut_diameter:float  = top_diameter - 0.05626*2\ncut_height:float  = base_height + top_height\n\nbase:cq.Workplane = cq.Workplane(\"XY\").circle(base_diameter/2).extrude(base_height)\ntop:cq.Workplane = cq.Workplane(\"XY\").circle(top_diameter/2).extrude(top_height)\ncut:cq.Workplane = cq.Workplane(\"XY\").circle(cut_diameter/2).extrude(cut_height)\n\npart:cq.Workplane = (\n    base\n    .union(top.translate((0, 0, base_height)))\n    .cut(cut)\n)\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.491,
  "chamfer_distance": 0.00011898760534496276,
  "bbox_similarity": 0.9998963866570983,
  "volume_ratio": 1.0048409980385957,
  "gt_volume": 0.09251912285773078,
  "gen_volume": 0.09296700775001765,
  "gt_bbox": [
    0.825,
    0.825,
    0.75
  ],
  "gen_bbox": [
    0.824999988079071,
    0.8247435688972473,
    0.75
  ]
}