{
  "id": "00997852",
  "category_semantic": "Moderate",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a tiered rectangular object with specific dimensions. First, create a base rectangle with dimensions 1.5 units in length, 0.153061 units in width, and 0.918367 units in height. Then, on top of this base, centered at the same point, sketch a smaller rectangle with dimensions 1.43878 units in length and 0.841837 units in height. Extrude this second rectangle upwards by 0.229592 units to form a tiered appearance, resembling a smaller rectangle placed on a larger rectangle.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 1.5\nwidth:float = 0.153061\nheight:float = 0.918367\n\ninner_length:float = 1.43878\ninner_width:float = 0.229592\ninner_height:float = 0.841837\n\n\nbox:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .box(length, width, height)\n    .faces(\"-Y\")\n    .workplane()\n    .rect(inner_length,inner_height)\n    .extrude(inner_width)\n)\n\npart:cq.Workplane = box.translate((0,-width/2,0))\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.415,
  "chamfer_distance": 8.840822068456472e-05,
  "bbox_similarity": 0.999999776184634,
  "volume_ratio": 1.0000013527646021,
  "gt_volume": 0.48893460470818884,
  "gen_volume": 0.4889352661216148,
  "gt_bbox": [
    1.5,
    0.38265310000000075,
    0.9183674
  ],
  "gen_bbox": [
    1.5,
    0.38265299797058105,
    0.9183670282363892
  ]
}