{
  "id": "00997068",
  "category_semantic": "Very Complex",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a rectangular object with specific dimensions. Start by creating a rectangle with a length of 0.00875 units, a width of 0.74801 units, and a height of 0.03125 units. Extrude this sketch to form the base object. Then, add a small rectangular cutout towards the bottom right side of the original rectangle. The cutout should have a width of 0.1625 units, a height of 0.0125 units, and should be positioned 0.01875 units from the left edge of the rectangle. This cutout should be approximately 1/4th the length of the original shape.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.00875\nwidth:float =  0.74801\nheight:float =  0.03125\ncut_width:float =  0.1625\ncut_height:float = 0.0125\nleft_offset:float = 0.01875\n\nrec:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .box(length, width, height)\n    .workplane(offset=-height/2+cut_height/2)\n    .center(0,-width/2+cut_width/2+left_offset)\n    .box(length,cut_width,cut_height, combine=\"cut\")\n)\n\npart:cq.Workplane = rec.translate((-length/2,width/2,height/2)).rotate((0,0,1),(0,0,0),180)\n\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.385,
  "chamfer_distance": 6.443652090584054e-06,
  "bbox_similarity": 0.9991155451252347,
  "volume_ratio": 0.9970948606978691,
  "gt_volume": 0.0001873046874999999,
  "gen_volume": 0.0001867605412908703,
  "gt_bbox": [
    0.00875,
    0.7500000000000001,
    0.03125
  ],
  "gen_bbox": [
    0.008750000037252903,
    0.748009979724884,
    0.03125
  ]
}