{
  "id": "00670454",
  "category_semantic": "Complex",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a rectangular object with specific dimensions. Start by creating a sketch of a rectangle with a length of 1.125 units, a width of 1.5 units, and extrude it to a height of 0.039474 units. Next, add two small holes on the left side of the rectangle. These holes should be positioned at the top and bottom of the object, each with a diameter of 0.059211 units. The holes should be inset from the edges by 0.108553 units in length and 0.098684 units in width. The final object should resemble a page with two holes from a hole-puncher, positioned for a binder.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 1.125\nwidth:float = 1.5\nheight:float = 0.039474\n\npadding_length:float = 0.108553\npadding_width:float = 0.098684\nhole_diameter:float = 0.059211\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .box(length,width,height).faces(\">Z\")\n    .workplane()\n    .rect(length - padding_length*2 - hole_diameter, width - padding_width*2 - hole_diameter, forConstruction=True)\n    .edges(\"<X\")\n    .vertices()\n    .hole(hole_diameter)\n)\n\npart = part.translate((0,0,height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.402,
  "chamfer_distance": 6.360919045467713e-05,
  "bbox_similarity": 0.9999973037590418,
  "volume_ratio": 1.00005079050402,
  "gt_volume": 0.0663955540544822,
  "gen_volume": 0.06639892631813732,
  "gt_bbox": [
    1.125,
    1.5,
    0.039473680000000046
  ],
  "gen_bbox": [
    1.125,
    1.5,
    0.0394739992916584
  ]
}