{
  "id": "00998283",
  "category_semantic": "Complex",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a long 3D trapezoidal prism with specific dimensions. Start by creating a sketch of an isosceles trapezium with a base length of 0.3 units, a top length of 0.225 units, and a height of 0.1875 units. Then, extrude this trapezium by 0.75 units to form the prism. Ensure the trapezium is centered and correctly oriented before extrusion.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nfrom typing import List,Tuple\n\nlength:float = 0.3\nwidth:float = 0.1875 \nheight:float = 0.75\ntop_length:float = 0.225\n\ntop_x:float = (length - top_length)/2\n\npoints:List[Tuple[float, float]] = [\n    (0, 0),\n    (length, 0),\n    (top_x + top_length, width),\n    (top_x, width),\n]\n\nwork:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .center(-length/2,-width/2)\n    .polyline(points).close()\n)\n\npart:cq.Workplane = work.extrude(height).translate((0.011705, 0.148443, 0))\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.382,
  "chamfer_distance": 7.229955821505219e-05,
  "bbox_similarity": 0.9999999966886308,
  "volume_ratio": 0.9999999971616834,
  "gt_volume": 0.036914062500000004,
  "gen_volume": 0.03691406239522621,
  "gt_bbox": [
    0.3,
    0.1875,
    0.75
  ],
  "gen_bbox": [
    0.29999999701976776,
    0.1875,
    0.75
  ]
}