{
  "id": "00009044",
  "category_semantic": "Moderate",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a cylinder with a height of 0.375 units and a diameter of 1.5 units. Include a small circular cutout at the center of the cylinder with a diameter of 0.237219 units.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nheight:float = 0.375\ndiameter:float = 1.5\nhole_diameter:float = 0.237219\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .cylinder(height, diameter/2)\n    .faces(\">Z\")\n    .hole(hole_diameter, height)\n)\n\npart = part.translate((0, 0, height/2)).rotate((1,0,0),(0,0,0),-90)\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.44,
  "chamfer_distance": 7.441058162279946e-05,
  "bbox_similarity": 0.9998963938819032,
  "volume_ratio": 1.0048952820009882,
  "gt_volume": 0.6427045259610211,
  "gen_volume": 0.6458507458589118,
  "gt_bbox": [
    1.5,
    0.3750000000000007,
    1.5
  ],
  "gen_bbox": [
    1.5,
    0.37500000000000006,
    1.499533772468567
  ]
}