{
  "id": "00002221",
  "category_semantic": "Complex",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a 3D model consisting of two extruded rectangles, each with a length of 0.0625 units, a width of 0.75 units, and a height of 0.0034 units. These rectangles should be connected at their edges, similar to the intersection between a wall and the floor, and positioned perpendicular to each other. The connection should occur along their elongated edge, forming a right angle between the two rectangles.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.0625\nwidth:float = 0.75\nheight:float = 0.0034\n\nrectangle:cq.Workplane = cq.Workplane(\"XY\").box(length, width, height)\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .union(rectangle.translate((-length/2+height/2,0,0)))\n    .union(rectangle.translate((-length/2+height/2,0,0)).rotate((0,1,0),(0,0,0),90))\n)\n\npart = part.translate((-height/2, -width/2, -height/2)).rotate((0, 0, 1),(0, 0, 0), -90)\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.43,
  "chamfer_distance": 1.9895953799026422e-05,
  "bbox_similarity": 0.9999999999999997,
  "volume_ratio": 0.8740388448120825,
  "gt_volume": 0.0003547668457031258,
  "gen_volume": 0.0003100800039959864,
  "gt_bbox": [
    0.75,
    0.06249999999999999,
    0.06250000000000006
  ],
  "gen_bbox": [
    0.75,
    0.0625,
    0.0625
  ]
}