{
  "id": "00997300",
  "category_semantic": "Complex",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a 3D cylindrical object with specific dimensions and multiple holes. First, create a large cylinder with a height of 0.375 units and a diameter of 1.5 units. Next, create a central hole through the cylinder with a diameter of 0.1875 units. Finally, add three smaller holes, each with a diameter of 0.1125 units, arranged in a triangular formation around the central hole. These smaller holes should be offset from the center by 0.24375 units towards the outer edge of the cylinder.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nheight:float = 0.375\ndiameter:float = 1.5\ninner_diameter:float = 0.1875\n\nbody:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .cylinder(height, diameter/2)\n    .cylinder(height, inner_diameter/2, combine=\"cut\")\n)\n\ncut_diameter:float = 0.1125\noffset:float = 0.24375\ncut_cylinder:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .cylinder(height, cut_diameter/2)\n    .translate((0,diameter/2-cut_diameter/2-offset,0))\n)\n\npart:cq.Workplane = (\n    body\n    .cut(cut_cylinder)\n    .cut(cut_cylinder.rotate((0,0,1),(0,0,0),120))\n    .cut(cut_cylinder.rotate((0,0,1),(0,0,0),-120))\n)\n\npart = part.translate((0,0,height/2))\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.533,
  "chamfer_distance": 7.890417318243075e-05,
  "bbox_similarity": 0.9998963938819038,
  "volume_ratio": 1.0047840720690766,
  "gt_volume": 0.6378925235107962,
  "gen_volume": 0.640944247315597,
  "gt_bbox": [
    1.5,
    1.5,
    0.375
  ],
  "gen_bbox": [
    1.5,
    1.499533772468567,
    0.375
  ]
}