{
  "id": "00001977",
  "category_semantic": "Moderate",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a right triangle with a base of 0.20312 units and a height of 0.20312 units, then extrude it to a height of 0.75 units. Rotate the resulting 3D object by -90 degrees around the Y-axis.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\nfrom typing import List,Tuple\n\nlength:float = 0.20312\nwidth:float = 0.20312\nextrude:float = 0.75\n\npts:List[Tuple[float, float]] = [\n    (0, 0),\n    (0, width),\n    (length, 0)\n]\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .polyline(pts)\n    .close()\n    .extrude(extrude)\n)\n\npart = part.rotate((0, 1, 0),(0, 0, 0), -90)\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.417,
  "chamfer_distance": 0.00011515785465226681,
  "bbox_similarity": 0.9738341970758058,
  "volume_ratio": 0.9215045254878108,
  "gt_volume": 0.0167895533203125,
  "gen_volume": 0.01547164936558687,
  "gt_bbox": [
    0.75,
    0.203125,
    0.22041670000000002
  ],
  "gen_bbox": [
    0.75,
    0.20311999320983887,
    0.20311999320983895
  ]
}