{
  "id": "00672291",
  "category_semantic": "Very Complex",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a long L-shaped bracket with specific dimensions. The bracket should have a main body with a length of 0.75 units, a width of 0.015 units, and a height of 0.3 units. Additionally, there should be a top extension on the bracket with a width of 0.15 units and a height equal to the main body's width. Start by drawing a sketch of an L shape and then extrude this sketch to form the 3D object.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.75\nwidth:float = 0.015\nheight:float = 0.3\n\ntop_width:float = 0.15\ntop_height:float = width\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .box(length,width,height)\n    .faces(\"Z\")\n    .workplane(offset=-top_height/2)\n    .center(0,top_width/2-width/2)\n    .box(length,top_width,top_height)\n)\n\npart = part.translate((length/2,width/2,-height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.387,
  "chamfer_distance": 6.55167892635114e-05,
  "bbox_similarity": 0.9999999735090468,
  "volume_ratio": 1.0000000195256582,
  "gt_volume": 0.004893750000000001,
  "gen_volume": 0.004893750095553691,
  "gt_bbox": [
    0.75,
    0.15,
    0.30000000000000004
  ],
  "gen_bbox": [
    0.75,
    0.15000000596046448,
    0.30000001192092896
  ]
}