{
  "id": "00038438",
  "category_semantic": "Moderate",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a rhombus with a length of 0.375 units and a width of 0.11438 units, and then extrude it to a height of 0.75 units.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\nfrom typing import List, Tuple\n\nlength:float = 0.375\nwidth:float = 0.11438\nheight:float = 0.75 \n\npoints:List[Tuple[float, float]] = [\n    (length/2, 0),\n    (length, width/2),\n    (length/2, width),\n    (0, width/2)\n]\n\npart:cq.Workplane = (\n    cq.Workplane(\"XZ\")\n    .polyline(points)\n    .close()\n    .extrude(height)\n)\n\npart = part.translate((-length/2, 0, 0))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.37,
  "chamfer_distance": 0.0001173338351565266,
  "bbox_similarity": 0.9999852939515567,
  "volume_ratio": 1.0000398513981978,
  "gt_volume": 0.016084046812559996,
  "gen_volume": 0.016084687784314156,
  "gt_bbox": [
    0.3750008,
    0.7500000000000002,
    0.11437519999999998
  ],
  "gen_bbox": [
    0.375,
    0.75,
    0.11438000202178955
  ]
}