{
  "id": "00685823",
  "category_semantic": "Complex",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a 3D object that resembles a square block with a circular cutout in one corner. Begin by defining a square with dimensions of length 0.668421 units and width 0.334211 units. Then, create a circular cutout with a diameter of 0.2625 units (70% of 0.375 units) positioned at the top-right corner of the square. Ensure that the circle's quadrant appears as if it has been removed from the corner. Finally, extrude this sketch to a height of 0.668421 units to form the 3D object.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.668421\nwidth:float = 0.334211\nheight:float = 0.668421\ndiameter:float = .375\n\ncut:cq.Workplane = cq.Workplane(\"XZ\").cylinder(width, diameter*.7)\nbox:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .box(length,width,height)\n    .cut(cut.translate((length/2-diameter/2+0.1,0,height/2-diameter/2+0.1)))\n)\n\npart:cq.Workplane = box.translate((-length/2-0.081579,-width/2,0.179688))\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.385,
  "chamfer_distance": 9.718569934652509e-05,
  "bbox_similarity": 0.9999992528987005,
  "volume_ratio": 1.0020006894196665,
  "gt_volume": 0.11339498593633945,
  "gen_volume": 0.11362185408494552,
  "gt_bbox": [
    0.6684213999999999,
    0.33421069999999997,
    0.6684215
  ],
  "gen_bbox": [
    0.6684210002422333,
    0.33421099185943604,
    0.6684209853410721
  ]
}