{
  "id": "00998843",
  "category_semantic": "Very Complex",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a tiered rectangular object with specific dimensions and a circular hole through the center of the upper section. Begin by creating a sketch of a rectangle with dimensions 0.5 units in length and 0.75 units in width, and then extrude it to a height of 0.15 units. Next, sketch another rectangle on top of the first, positioned at one end, with the same length of 0.5 units but a reduced width of 0.35 units. Extrude this second rectangle upwards by 0.15 units to form a smaller block on top of the larger base, giving the appearance of a staircase. Finally, create a circular hole with a diameter of 0.2 units through the center of the upper rectangular block, ensuring the hole passes through both the upper and lower blocks. Adjust the position of the entire model so that its geometric center aligns with the origin of the coordinate system.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\nlength = 0.5\nwidth = 0.75\nheight = 0.15\n\nbase = cq.Workplane(\"XY\").box(length, width, height)\n\ns_length = 0.35\ns_height = 0.15\ndiameter = 0.2\n\n\npart = (\n    base\n    .faces(\"Z\")\n    .workplane()\n    .center(length/2-s_length/2,0)\n    .rect(s_length, width)\n    .extrude(s_height)\n    .faces(\">Z\")\n    .workplane()\n    .circle(diameter/2)\n    .extrude(-(height+s_height),combine=\"cut\")\n)\n\npart = part.translate((length/2,width/2,height/2))\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.428,
  "chamfer_distance": 0.00010912644220440725,
  "bbox_similarity": 0.9999999867545232,
  "volume_ratio": 0.9996271629283083,
  "gt_volume": 0.08624799806649595,
  "gen_volume": 0.08621584161545758,
  "gt_bbox": [
    0.5000000000000003,
    0.75,
    0.3
  ],
  "gen_bbox": [
    0.5,
    0.75,
    0.30000001192092896
  ]
}