{
  "id": "00980651",
  "category_semantic": "Complex",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a hexagon with 6 sides and a side length of 1.47802 units, extrude it to a height of 0.5 units, and then create a cylinder with a diameter of 1.2 units and a height of 0.25 units. Place the cylinder on top of the hexagon and ensure that the cylinder is extruded to half the height of the hexagon.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\ndiameter:float = 1.2\ncylinder_length:float = 0.25\n\nsides:int = 6\nlength:float = 1.47802\nextrude:float = 0.5\n\ncylinder = cq.Workplane(\"XZ\").cylinder(cylinder_length, diameter/2)\npart:cq.Workplane = cylinder.faces(\"-Y\").polygon(sides, length).workplane().extrude(extrude)\n\npart = part.translate((0,cylinder_length/2+extrude,0))\npart = part.rotate((1,0,0),(0,0,0),-90)\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.415,
  "chamfer_distance": 8.515314981926309e-05,
  "bbox_similarity": 0.9999985062498975,
  "volume_ratio": 1.0013310408397857,
  "gt_volume": 0.9907585782586948,
  "gen_volume": 0.9920773183887253,
  "gt_bbox": [
    1.4780166,
    1.28,
    0.75
  ],
  "gen_bbox": [
    1.4780199527740479,
    1.2800028324127197,
    0.7500000000000001
  ]
}