{
  "id": "00520150",
  "category_semantic": "Complex",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create an \"L\" shaped object with a length of 0.75 units, a width of 0.75 units, and a height of 0.1875 units, and then extrude it.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.75\nwidth:float = 0.75\nheight:float = 0.1875\n\nrectangle:cq.Workplane = cq.Workplane(\"XY\").box(length, width, height)\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .union(rectangle.translate((-length/2+height/2,0,0)))\n    .union(rectangle.translate((-length/2+height/2,0,0)).rotate((0,1,0),(0,0,0),90))\n)\n\npart = (\n    part.translate((-height/2,0,-height/2))\n    .rotate((0,1,0),(0,0,0),180)\n    .rotate((0,0,1),(0,0,0),90)\n    .translate((length/2-0.042461,0,0))\n)\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.41,
  "chamfer_distance": 0.00010201425175540041,
  "bbox_similarity": 0.999999741176939,
  "volume_ratio": 1.000000547897779,
  "gt_volume": 0.18457021687501207,
  "gen_volume": 0.18457031800062396,
  "gt_bbox": [
    0.7499998400000001,
    0.7499998000000001,
    0.7499998
  ],
  "gen_bbox": [
    0.7500000223517418,
    0.75,
    0.7500000000000001
  ]
}