{
  "id": "00986712",
  "category_semantic": "Complex",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a 3D object based on the following specifications: Start by creating a sketch of a rectangle with a length of 0.875 units and a width of 0.15 units. Round two corners of the same long edge of the rectangle with a fillet radius of 0.25 units. Then, extrude this sketch to a height of 1.5 units. Finally, create two small, evenly-spaced circular holes on the same side as the rounded corners. Each of these holes should have a diameter of 0.3 units and be positioned close to one of the rounded corners. Adjust the placement of the holes by adding a padding of approximately -0.639071 units to the length and height dimensions of the rectangle during the hole creation process.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.875\nwidth:float = 0.15\nheight:float = 1.5\nfillet:float = 0.25\ndiameter:float = 0.3\npadding:float = -.65+ 0.035355 - 0.007163 - 0.002263\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .box(length, width, height)\n    .tag(\"body\")\n    .faces(\">Y\")\n    .workplane()\n    .rect(length+padding, height+padding, forConstruction=True)\n    .edges(\"Z\")\n    .vertices()\n    .circle(diameter/2).extrude(-width, combine = \"cut\")\n    .faces(\"-X\", tag=\"body\")\n    .edges(\"|Y\")\n    .fillet(fillet)\n)\n\npart = part.translate((0,-width/2,0))\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.45,
  "chamfer_distance": 6.696109264047081e-05,
  "bbox_similarity": 0.9999999867545243,
  "volume_ratio": 0.9998643088994685,
  "gt_volume": 0.17167831092879718,
  "gen_volume": 0.17165501570984987,
  "gt_bbox": [
    0.875,
    0.1500000000000004,
    1.5
  ],
  "gen_bbox": [
    0.875,
    0.15000000596046448,
    1.5
  ]
}