{
  "id": "00031181",
  "category_semantic": "Complex",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a rectangular prism with a length of 0.61135 meters, a width of 0.36026 meters, and a height of 0.33843 meters. The object should be centered at the origin.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.61135\nwidth:float = 0.36026\nheight:float =  0.33843\n\npart:cq.Workplane = cq.Workplane(\"XY\").box(length, width, height)\n\npart = part.translate((length/2, width/2, height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.365,
  "chamfer_distance": 0.00011284056719933018,
  "bbox_similarity": 0.9999940850904091,
  "volume_ratio": 0.9999945912763114,
  "gt_volume": 0.07453790116236104,
  "gen_volume": 0.07453749800744933,
  "gt_bbox": [
    0.6113537,
    0.360262,
    0.3384279
  ],
  "gen_bbox": [
    0.6113499999046326,
    0.360260009765625,
    0.3384299874305725
  ]
}