{
  "id": "00984488",
  "category_semantic": "Moderate",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a 3D object. Begin by drawing a sketch of a square with a length and width of 0.86802 units. Next, modify the sketch by attaching a semi-circle with a diameter of 0.86802 units to the top of the square, ensuring that the flat side of the semi-circle aligns perfectly with the top edge of the square. Finally, extrude this entire sketch to a height of 0.152284 units to form the 3D object.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nheight:float = 0.152284\ncylinder_diameter:float = 0.86802\ncylinder:cq.Workplane = cq.Workplane(\"XY\").cylinder(height, cylinder_diameter/2)\n\nrec_length:float = 0.63198\nrec_width:float = cylinder_diameter\nrec:cq.Workplane = cq.Workplane(\"XY\").box(rec_length, rec_width, height)\n\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .union(cylinder)\n    .union(rec.translate((-rec_length/2,0, 0)))\n)\n\npart = part.translate((rec_length/2, 0, height/2)).rotate((0,0,1),(0,0,0),-90)\n\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.409,
  "chamfer_distance": 7.319828890780758e-05,
  "bbox_similarity": 0.9999571422034668,
  "volume_ratio": 1.001631920410819,
  "gt_volume": 0.12836864406529122,
  "gen_volume": 0.12857813147565053,
  "gt_bbox": [
    0.8680202,
    1.0659898,
    0.15228430000000004
  ],
  "gen_bbox": [
    0.8680199980735779,
    1.0658551156520844,
    0.15228399634361267
  ]
}