{
  "id": "00670334",
  "category_semantic": "Complex",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a rectangular object with specific dimensions. First, create a sketch of a rectangle with a length of 0.75 units, a width of 0.4 units, and then extrude it to a height of 0.2375 units. Next, add a circular hole at the center of the rectangle with a diameter of 0.11875 units.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\nlength:float = .75\nwidth:float = 0.4\nheight:float = 0.2375\ndiameter:float = 0.11875\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .box(length, width, height)\n    .cylinder(height, diameter/2, combine=\"cut\")\n)\n\npart = part.translate((-length/2, width/2, height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.367,
  "chamfer_distance": 9.785746575725482e-05,
  "bbox_similarity": 0.9999999908501648,
  "volume_ratio": 0.9999801268997552,
  "gt_volume": 0.06863294013710407,
  "gen_volume": 0.06863157618780463,
  "gt_bbox": [
    0.75,
    0.40000000000000074,
    0.23750000000000002
  ],
  "gen_bbox": [
    0.75,
    0.4000000059604645,
    0.23749999701976776
  ]
}