{
  "id": "00670441",
  "category_semantic": "Moderate",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a regular octagon with each side measuring 1.00328 units, then extrude it to a height of 0.271665 units. After extrusion, rotate the object 22.4 degrees around the Z-axis and -90 degrees around the X-axis, then translate it to the position (-0.176576, 0, 0.286546).",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nsides:int = 8\nlength:float = 1.00328\nextrude:float = 0.271665\n\npart:cq.Workplane = cq.Workplane(\"XY\").polygon(sides, length).extrude(extrude)\n\npart = part.rotate((0,0,1),(0,0,0),22.4).rotate((1,0,0),(0,0,0),-90).translate((-0.176576,0,0.286546))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.384,
  "chamfer_distance": 7.920455986911446e-05,
  "bbox_similarity": 0.999519340061267,
  "volume_ratio": 0.999999143522199,
  "gt_volume": 0.1933585491799589,
  "gen_volume": 0.1933583835726539,
  "gt_bbox": [
    0.9269103,
    0.27166500000000027,
    0.9269102
  ],
  "gen_bbox": [
    0.9275785088539124,
    0.2716650068759919,
    0.9275785535573959
  ]
}