{
  "id": "00007258",
  "category_semantic": "Simple",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a rectangular prism with a length of 0.19091 units, a width of 0.01705 units, and a height of 0.75 units. The prism should be positioned such that its center aligns with the origin in the 3D space.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.19091\nwidth:float = 0.01705\nheight:float = 0.75\n\npart:cq.Workplane = cq.Workplane(\"XY\").box(length, width, height)\n\npart = part.translate((length/2, -width/2, height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.407,
  "chamfer_distance": 3.333157876401321e-05,
  "bbox_similarity": 0.9999094584629747,
  "volume_ratio": 1.0002716258647424,
  "gt_volume": 0.002440598638946262,
  "gen_volume": 0.002441261568662055,
  "gt_bbox": [
    0.1909091,
    0.01704545000000018,
    0.75
  ],
  "gen_bbox": [
    0.1909099966287613,
    0.0170499999076128,
    0.75
  ]
}