{
  "id": "00008315",
  "category_semantic": "Simple",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a rectangular prism with a length of 0.75 units, a width of 0.0075 units, and a height of 0.075 units. The prism should be positioned such that its center aligns with the origin of the coordinate system.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.75\nwidth:float = 0.0075\nheight:float = 0.075\n\npart:cq.Workplane = cq.Workplane(\"XY\").box(length, width, height)\n\npart = part.translate((length/2, -width/2, height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.373,
  "chamfer_distance": 1.3887683565450906e-05,
  "bbox_similarity": 0.9999999793039113,
  "volume_ratio": 1.0000000173846397,
  "gt_volume": 0.00042187500000002005,
  "gen_volume": 0.0004218750073341649,
  "gt_bbox": [
    0.75,
    0.007500000000000712,
    0.07500000000000004
  ],
  "gen_bbox": [
    0.75,
    0.007499999832361937,
    0.07500000298023224
  ]
}