{
  "id": "00682073",
  "category_semantic": "Complex",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a \"U\"-shaped object. Begin by creating a rectangular sketch with dimensions 0.75 units in length, 0.5 units in width, and extrude it to a height of 0.75 units. Next, sketch another rectangle with dimensions 0.25 units in length and 0.5 units in height. Position this rectangle in the middle of the first rectangle, aligned with the top edge. Then, negatively extrude this smaller rectangle by 0.25 units to create a cutout in the original rectangular block, effectively forming a \"U\" shape.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.75\nwidth:float = 0.5\nheight:float = 0.75\n\ndim_length:float = 0.25\ndim_height:float = 0.5\n\n\ncube:cq.Workplane = cq.Workplane(\"XY\").box(dim_length,width,dim_height)\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\").box(length, width, height)\n    .cut(cube.translate((0,0,00.25/2)))\n)\n\npart = part.translate((0.172956,-width/2,height/2))\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.431,
  "chamfer_distance": 0.00013230761357231404,
  "bbox_similarity": 0.9999999933772613,
  "volume_ratio": 0.9999999872275757,
  "gt_volume": 0.2187500000000001,
  "gen_volume": 0.21874999720603228,
  "gt_bbox": [
    0.75,
    0.5000000000000006,
    0.75
  ],
  "gen_bbox": [
    0.7499999850988388,
    0.5,
    0.75
  ]
}