{
  "id": "00520321",
  "category_semantic": "Complex",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create an object that resembles a lego block. Begin by creating a rectangular prism with a length of 1.23418 units, a width of 0.617188 units (which is half the length), and a height of 0.75 units. Then, create two short cylinders, each with a height of 0.140625 units and a diameter of 0.380469 units, which is approximately a quarter of the size of the rectangular prism. These cylinders should be parallel to each other and positioned symmetrically at the bottom of the rectangular prism, connected at its center. The cylinders should be spaced apart from each other by a distance that includes a padding of 0.118359 units from the edges of the length of the prism.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 1.23418\nwidth:float = 0.617188\nheight:float = 0.75\n\nrectangle:cq.Workplane = cq.Workplane(\"XY\").box(length, width, height)\n\ncylinder_height:float = 0.140625\ndiameter:float = 0.380469\ncylinder:cq.Workplane = cq.Workplane(\"XY\").cylinder(cylinder_height, diameter/2)\n\npadding:float = 0.118359\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .union(rectangle)\n    .union(cylinder.translate((-(length/2-diameter/2 - padding),0,-(height/2+cylinder_height/2))))\n    .union(cylinder.translate(((length/2-diameter/2 - padding),0,-(height/2+cylinder_height/2))))\n)\n\npart = part.translate((0,0,height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.477,
  "chamfer_distance": 0.0001079934756236447,
  "bbox_similarity": 0.9999471311198246,
  "volume_ratio": 1.0000954942033398,
  "gt_volume": 0.6031943369272614,
  "gen_volume": 0.6032519384899254,
  "gt_bbox": [
    1.234375,
    0.6171876,
    0.890625
  ],
  "gen_bbox": [
    1.234179973602295,
    0.6171879768371582,
    0.890625
  ]
}