{
  "id": "00033624",
  "category_semantic": "Complex",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a long rectangle with a length of 0.21429 units, a width of 0.75 units, and a height of 0.21429 units, and extrude it. Next, create two cylindrical holes each with a diameter of 0.05371 units, positioning them close to each end of the rectangle, ensuring there is a padding of 0.048699 units from the edges of the rectangle to the center of the holes.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.21429\nwidth:float =  0.75\nheight:float =  0.21429\n\nrec:cq.Workplane = cq.Workplane(\"XY\").box(length, width, height)\n\ndiameter:float = 0.05371\ncylinder:cq.Workplane = cq.Workplane(\"XY\").cylinder(length, diameter/2).rotate((0,1,0),(0, 0, 0),90)\n\nside_padding:float = 0.048699\n\npart:cq.Workplane = (\n    rec\n    .cut(cylinder.translate((0,-width/2 + diameter/2 + side_padding,0)))\n    .cut(cylinder.translate((0,width/2 - diameter/2 - side_padding,0)))\n)\n\npart = part.translate((length/2, width/2, height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.401,
  "chamfer_distance": 9.209222950522045e-05,
  "bbox_similarity": 0.9999866438506665,
  "volume_ratio": 1.0004007671131265,
  "gt_volume": 0.033477662511700805,
  "gen_volume": 0.033491079257859845,
  "gt_bbox": [
    0.21428570000000072,
    0.75,
    0.21428570000000005
  ],
  "gen_bbox": [
    0.21428999304771423,
    0.75,
    0.21428999304771423
  ]
}