{
  "id": "00672352",
  "category_semantic": "Complex",
  "category_mesh": "Complex",
  "prompt": "Write Python code using CADQuery to create a rectangular object with specific dimensions. The rectangle should have a length of 0.75 units, a width of 0.375 units, and be extruded to a height of 0.015611 units. After creating the rectangle, add a small circular hole in the top right corner. The hole should have a diameter of 0.09375 units and be positioned with a padding of 0.015625 units from both the right and top edges of the rectangle.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\nlength:float = 0.75\nwidth:float = 0.375\nheight:float = 0.015611\n\ndiameter:float = 0.09375\npadding:float = 0.015625\ncylinder:cq.Workplane = cq.Workplane(\"XY\").cylinder(height, diameter/2)\n\npart:cq.Workplane = (\n    cq.Workplane(\"XY\")\n    .box(length,width,height)\n    .cut(cylinder.translate((length/2-diameter/2-padding,+width/2-diameter/2-padding,0)))\n)\n\npart = part.translate((-length/2,-width/2,height/2))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.404,
  "chamfer_distance": 5.305500848418734e-05,
  "bbox_similarity": 0.9997013409932448,
  "volume_ratio": 0.9991599629449842,
  "gt_volume": 0.004287219984648185,
  "gen_volume": 0.0042836185609980764,
  "gt_bbox": [
    0.7500000000000001,
    0.37500000000000006,
    0.015625000000000024
  ],
  "gen_bbox": [
    0.75,
    0.375,
    0.01561100035905838
  ]
}