{
  "id": "00520130",
  "category_semantic": "Complex",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a grooved rectangle. Begin by creating a rectangle in the X-Y plane with dimensions 1.05 units in length and 0.375 units in width, and extrude it along the Z-axis to a height of 0.9 units. Next, create two sketches of smaller rectangles, each with dimensions 0.6 units in length and 0.15 units in width. Attach these sketches to the left and right sides of the initial rectangle. Extrude both smaller rectangles to the same height of 0.9 units, but in the opposite direction such that they protrude outwards from the main rectangle.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 1.05\nwidth:float = 0.375\nheight:float = 0.9\n\nbox:cq.Workplane = cq.Workplane(\"XY\").box(length, width, height)\n\ncut_length:float = 0.6\ncut_width:float = 0.15\ncut_box:cq.Workplane = cq.Workplane(\"XY\").box(cut_length, cut_width, height)\n\npart:cq.Workplane = box.cut(cut_box.translate((0, -width/2 + cut_width/2, 0)))\n\npart = part.translate((0, 0, height/2)).rotate((0, 0, 1),(0, 0, 0), -90).translate((-0.062655,-0.075414,0))\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.377,
  "chamfer_distance": 0.0001058333698372683,
  "bbox_similarity": 0.9999998966041843,
  "volume_ratio": 0.9999999499615335,
  "gt_volume": 0.273375,
  "gen_volume": 0.2733749863207342,
  "gt_bbox": [
    0.3750001,
    1.0499999999999998,
    0.9
  ],
  "gen_bbox": [
    0.375,
    1.0499999821186066,
    0.8999999761581421
  ]
}