{
  "id": "00003558",
  "category_semantic": "Simple",
  "category_mesh": "Simple",
  "prompt": "Write Python code using CADQuery to create a rectangular prism with a length of 0.59437 units, a width of 0.44577 units, and a height of 0.37148 units.",
  "mode": "code-only",
  "generated_code": "import cadquery as cq\n\nlength:float = 0.59437\nwidth:float =  0.44577\nheight:float = 0.37148\n\npart:cq.Workplane = cq.Workplane(\"XY\").box(length, width, height)\n\ncq.exporters.export(part, 'Ground_Truth.stl')",
  "execution_success": true,
  "execution_error": null,
  "execution_time_s": 1.376,
  "chamfer_distance": 0.00011863481932652984,
  "bbox_similarity": 0.9999931386020346,
  "volume_ratio": 1.0000017200860343,
  "gt_volume": 0.09842431372736694,
  "gen_volume": 0.09842448302565443,
  "gt_bbox": [
    0.5943656,
    0.4457742,
    0.3714786
  ],
  "gen_bbox": [
    0.5943700075149536,
    0.4457699954509735,
    0.37147998809814453
  ]
}